### ISSUE TITLE
Use GitHub Pages 

### ISSUE THREAD

**Issue by jaroshevskii** [limanp/My_blog_site#1]
Хорошой идеей было бы воспользоваться бесплатным хостингом для сайта с помощью GitHub Pages. Это просто и не требует особых усилий.

Более подробно узнать что такое GitHub Pages можно на их сайте: https://pages.github.com/

Для того чтобы начать использовать GitHub Pages можно воспользоваться Quickstart страничкой на сайте документации: https://docs.github.com/en/pages/quickstart

**Comment by limanp** [comment]
Ок, воспользуюсь

**Comment by jaroshevskii** [comment]
Также для удобства ссылку на страницу можно прописать в описание репозитория

![Screenshot_20220815_093316](https://user-images.githubusercontent.com/72662383/184588114-95148e67-4725-497b-976a-977e7f87bf0a.jpg)
![Screenshot_20220815_093442](https://user-images.githubusercontent.com/72662383/184588120-c9e03080-2bca-4433-891b-00cf713bfa3d.jpg)
