### ISSUE TITLE
[Bug] Синяя полоса на заднем фоне

### ISSUE THREAD

**Issue by jaroshevskii** [limanp/My_blog_site#2]
После добавления анимированиго заднего фото (который кстати очень симпатично выглядит), появился странный баг. В левой части экрана  (примерно в середине анимации) появляется синяя полоса на секунду и попадает. Баг можно заменить только если открыть страницу на телефоне.

![Screenshot_20220822_014344_com android chrome](https://user-images.githubusercontent.com/72662383/185814431-2aa78726-8ede-4b97-a232-3c6fe9b43e0f.jpg)

**Comment by limanp** [comment]
<h1>[Bug] - был исправлен.</h1>
Тепер смартфоная версия работает как надо.<br>
Спасибо за нахождение ошыбок в проекте!

**Comment by jaroshevskii** [comment]
> # [Bug] - был исправлен.
> Тепер смартфоная версия работает как надо.
> Спасибо за нахождение ошыбок в проекте!

Всегда рад помочь 🤠
